### ISSUE TITLE
Do not override the default stylesheet

### ISSUE THREAD

**Issue by thelfensdrfer** [mdmsoft/yii2-admin#11]
I think you should prefix your classes and especially remove this part from the stylesheet:

``` css
body {
    padding-top: 70px;
}
```
